name: CI-CD Comments Microservices

on:
  push:
    branches: [main, test]
    paths:
      - 'add-comment-ms/add-comment-ms/**'
      - 'delete-comment-ms/delete-comment-ms/**'
      - 'edit-comment-ms/edit-comment-ms/**'
      - 'list-comment-ms/list-comment-ms/**'
  pull_request:
    branches: [main]
    paths:
      - 'add-comment-ms/add-comment-ms/**'
      - 'delete-comment-ms/delete-comment-ms/**'
      - 'edit-comment-ms/edit-comment-ms/**'
      - 'list-comment-ms/list-comment-ms/**'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_NAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  #### 1. TESTS ####
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - add-comment-ms
          - delete-comment-ms
          - edit-comment-ms
          - list-comment-ms
    steps:
      - uses: actions/checkout@v4
      - name: Should Run Test?
        id: should_run
        run: echo "should_run=$(echo '${{ github.event.head_commit.message }}' | grep -q '${{ matrix.service }}' && echo true || echo false)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Run static check
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        run: bash ${{ matrix.service }}/${{ matrix.service }}/tests/check-static.sh

  #### 2. BUILD ####
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service:
          - add-comment-ms
          - delete-comment-ms
          - edit-comment-ms
          - list-comment-ms
    steps:
      - uses: actions/checkout@v4
      - name: Should Run Build?
        id: should_run
        run: echo "should_run=$(echo '${{ github.event.head_commit.message }}' | grep -q '${{ matrix.service }}' && echo true || echo false)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Build Docker image
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        run: |
          docker build -t alexismendozaa/${{ matrix.service }}:latest ./${{ matrix.service }}/${{ matrix.service }}
      - name: Save Docker image artifact
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        run: docker save alexismendozaa/${{ matrix.service }}:latest -o ${{ matrix.service }}.tar
      - uses: actions/upload-artifact@v4
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        with:
          name: ${{ matrix.service }}-image
          path: ${{ matrix.service }}.tar

  #### 3. PUSH ####
  push:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        service:
          - add-comment-ms
          - delete-comment-ms
          - edit-comment-ms
          - list-comment-ms
    steps:
      - uses: actions/checkout@v4
      - name: Should Run Push?
        id: should_run
        run: echo "should_run=$(echo '${{ github.event.head_commit.message }}' | grep -q '${{ matrix.service }}' && echo true || echo false)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/download-artifact@v4
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        with:
          name: ${{ matrix.service }}-image

      - name: Load Docker image
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        run: docker load -i ${{ matrix.service }}.tar

      - name: Login to Docker Hub
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        run: docker push alexismendozaa/${{ matrix.service }}:latest

  #### 4. DEPLOY ####
  deploy:
    runs-on: ubuntu-latest
    needs: push
    strategy:
      matrix:
        service:
          - add-comment-ms
          - delete-comment-ms
          - edit-comment-ms
          - list-comment-ms
    steps:
      - name: Should Run Deploy?
        id: should_run
        run: echo "should_run=$(echo '${{ github.event.head_commit.message }}' | grep -q '${{ matrix.service }}' && echo true || echo false)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Seleccionar ambiente y SSH key
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        id: select-env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "host=${{ secrets.EC2_QA }}" >> $GITHUB_OUTPUT
            echo "key=${{ secrets.SSH_KEY_QA }}" >> $GITHUB_OUTPUT
          else
            echo "host=${{ secrets.EC2_PROD }}" >> $GITHUB_OUTPUT
            echo "key=${{ secrets.SSH_KEY_PROD }}" >> $GITHUB_OUTPUT
          fi

      - name: Deploy updated microservice to EC2 via SSH
        if: steps.should_run.outputs.should_run == 'true' || github.event_name == 'pull_request'
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ steps.select-env.outputs.host }}
          username: ubuntu
          key: ${{ steps.select-env.outputs.key }}
          port: 22
          script: |
            docker rm -f ${{ matrix.service }} || true

            export DB_COMMENTS='${{ secrets.DB_COMMENTS }}'
            export DB_HOST='${{ secrets.DB_HOST }}'
            export DB_NAME='${{ secrets.DB_NAME }}'
            export DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
            export DB_PORT='${{ secrets.DB_PORT }}'
            export DB_SSL='${{ secrets.DB_SSL }}'
            export DB_USER='${{ secrets.DB_USER }}'
            export DB_USERS='${{ secrets.DB_USERS }}'
            export JWT_SECRET='${{ secrets.JWT_SECRET }}'

            if [ "${{ matrix.service }}" = "add-comment-ms" ]; then
              docker run -d --name add-comment-ms \
                -p 5019:3019 \
                -e DB_COMMENTS=$DB_COMMENTS \
                -e DB_HOST=$DB_HOST \
                -e DB_NAME=$DB_NAME \
                -e DB_PASSWORD=$DB_PASSWORD \
                -e DB_PORT=$DB_PORT \
                -e DB_SSL=$DB_SSL \
                -e DB_USER=$DB_USER \
                -e DB_USERS=$DB_USERS \
                -e JWT_SECRET=$JWT_SECRET \
                alexismendozaa/add-comment-ms:latest

            elif [ "${{ matrix.service }}" = "delete-comment-ms" ]; then
              docker run -d --name delete-comment-ms \
                -p 5021:3021 \
                -e DB_COMMENTS=$DB_COMMENTS \
                -e DB_HOST=$DB_HOST \
                -e DB_NAME=$DB_NAME \
                -e DB_PASSWORD=$DB_PASSWORD \
                -e DB_PORT=$DB_PORT \
                -e DB_SSL=$DB_SSL \
                -e DB_USER=$DB_USER \
                -e DB_USERS=$DB_USERS \
                -e JWT_SECRET=$JWT_SECRET \
                alexismendozaa/delete-comment-ms:latest

            elif [ "${{ matrix.service }}" = "edit-comment-ms" ]; then
              docker run -d --name edit-comment-ms \
                -p 5020:3020 \
                -e DB_COMMENTS=$DB_COMMENTS \
                -e DB_HOST=$DB_HOST \
                -e DB_NAME=$DB_NAME \
                -e DB_PASSWORD=$DB_PASSWORD \
                -e DB_PORT=$DB_PORT \
                -e DB_SSL=$DB_SSL \
                -e DB_USER=$DB_USER \
                -e DB_USERS=$DB_USERS \
                -e JWT_SECRET=$JWT_SECRET \
                alexismendozaa/edit-comment-ms:latest

            elif [ "${{ matrix.service }}" = "list-comment-ms" ]; then
              docker run -d --name list-comment-ms \
                -p 5022:3022 \
                -e DB_COMMENTS=$DB_COMMENTS \
                -e DB_HOST=$DB_HOST \
                -e DB_NAME=$DB_NAME \
                -e DB_PASSWORD=$DB_PASSWORD \
                -e DB_PORT=$DB_PORT \
                -e DB_SSL=$DB_SSL \
                -e DB_USER=$DB_USER \
                -e DB_USERS=$DB_USERS \
                -e JWT_SECRET=$JWT_SECRET \
                alexismendozaa/list-comment-ms:latest
            fi

            docker image prune -af